import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


const Pretendard = localFont({
  src: "./fonts/PretendardVariable.ttf",
  variable: "--font-pretendard",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width,initial-scale=1",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={` ${Pretendard.variable} font-sans antialiased`}
      >
        <div id="__next">{children}</div>
      </body>
    </html>
  );
}
